<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRNyYpyr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRNyYpyr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRNyYpyr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRNyYpyr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRNyYpyr\App_KernelDevDebugContainer([
    'container.build_hash' => 'RNyYpyr',
    'container.build_id' => 'df21702a',
    'container.build_time' => 1643115936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRNyYpyr');
