<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF3ss8WP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF3ss8WP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF3ss8WP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF3ss8WP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF3ss8WP\App_KernelDevDebugContainer([
    'container.build_hash' => 'F3ss8WP',
    'container.build_id' => '1fc34ff4',
    'container.build_time' => 1643088576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF3ss8WP');
