<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'asdasd' => [['hash'], ['_controller' => 'App\\Controller\\IndexController::access'], [], [['variable', '/', '[^/]++', 'hash', true], ['text', '/access']], [], [], []],
    'most-accesseds' => [[], ['_controller' => 'App\\Controller\\IndexController::mostAccessed'], [], [['text', '/most-accessed']], [], [], []],
    'links_index' => [[], ['_controller' => 'App\\Controller\\LinkController::index'], [], [['text', '/short']], [], [], []],
    'links_create' => [[], ['_controller' => 'App\\Controller\\LinkController::save'], [], [['text', '/short']], [], [], []],
    'links_find' => [['id'], ['_controller' => 'App\\Controller\\LinkController::find'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/links']], [], [], []],
    'links_update' => [['id'], ['_controller' => 'App\\Controller\\LinkController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/links']], [], [], []],
    'links_delete' => [['id'], ['_controller' => 'App\\Controller\\LinkController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/links']], [], [], []],
];
