<?php

namespace ContainerRNyYpyr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBapjZXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QBapjZX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QBapjZX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\LinksRepository', 'getLinksRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\LinksRepository',
        ]);
    }
}
