<?php

namespace ContainerRNyYpyr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W0bJ1dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._w0bJ1d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._w0bJ1d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'link' => ['privates', '.errored..service_locator._w0bJ1d.App\\Entity\\Links', NULL, 'Cannot autowire service ".service_locator._w0bJ1d": it references class "App\\Entity\\Links" but no such service exists.'],
        ], [
            'link' => 'App\\Entity\\Links',
        ]);
    }
}
