<?php

namespace ContainerRNyYpyr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PC_qafz.App\Entity\Links' shared service.
     *
     * @return \App\Entity\Links
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PC_qafz": it references class "App\\Entity\\Links" but no such service exists.');
    }
}
