<?php

namespace ContainerRNyYpyr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LinkSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LinkSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LinkSubscriber.php';

        return $container->privates['App\\EventSubscriber\\LinkSubscriber'] = new \App\EventSubscriber\LinkSubscriber();
    }
}
