<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMibux8S\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMibux8S/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMibux8S.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMibux8S\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerMibux8S\App_KernelTestDebugContainer([
    'container.build_hash' => 'Mibux8S',
    'container.build_id' => 'cd464590',
    'container.build_time' => 1640746294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMibux8S');
