<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIZGyxService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.j_iZGyx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j_iZGyx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DepartmentController::create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\DepartmentController::delete' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\DepartmentController::index' => ['privates', '.service_locator.XUGIeC7', 'get_ServiceLocator_XUGIeC7Service', true],
            'App\\Controller\\SecurityController::createPasswordForm' => ['privates', '.service_locator.iFdNKOw', 'get_ServiceLocator_IFdNKOwService', true],
            'App\\Controller\\SecurityController::getAuthCookie' => ['privates', '.service_locator.nBk1zMX', 'get_ServiceLocator_NBk1zMXService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.JFkiU6M', 'get_ServiceLocator_JFkiU6MService', true],
            'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.iSGa_mG', 'get_ServiceLocator_ISGaMGService', true],
            'App\\Controller\\SecurityController::rescue' => ['privates', '.service_locator.CvGpC2m', 'get_ServiceLocator_CvGpC2mService', true],
            'App\\Controller\\SecurityController::reset' => ['privates', '.service_locator.59UalJ3', 'get_ServiceLocator_59UalJ3Service', true],
            'App\\Controller\\TaskController::create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.L392EaH', 'get_ServiceLocator_L392EaHService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DepartmentController:create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\DepartmentController:delete' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\DepartmentController:index' => ['privates', '.service_locator.XUGIeC7', 'get_ServiceLocator_XUGIeC7Service', true],
            'App\\Controller\\SecurityController:createPasswordForm' => ['privates', '.service_locator.iFdNKOw', 'get_ServiceLocator_IFdNKOwService', true],
            'App\\Controller\\SecurityController:getAuthCookie' => ['privates', '.service_locator.nBk1zMX', 'get_ServiceLocator_NBk1zMXService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.JFkiU6M', 'get_ServiceLocator_JFkiU6MService', true],
            'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.iSGa_mG', 'get_ServiceLocator_ISGaMGService', true],
            'App\\Controller\\SecurityController:rescue' => ['privates', '.service_locator.CvGpC2m', 'get_ServiceLocator_CvGpC2mService', true],
            'App\\Controller\\SecurityController:reset' => ['privates', '.service_locator.59UalJ3', 'get_ServiceLocator_59UalJ3Service', true],
            'App\\Controller\\TaskController:create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.L392EaH', 'get_ServiceLocator_L392EaHService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.lqzS9y4', 'get_ServiceLocator_LqzS9y4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DepartmentController::create' => '?',
            'App\\Controller\\DepartmentController::delete' => '?',
            'App\\Controller\\DepartmentController::index' => '?',
            'App\\Controller\\SecurityController::createPasswordForm' => '?',
            'App\\Controller\\SecurityController::getAuthCookie' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::register' => '?',
            'App\\Controller\\SecurityController::rescue' => '?',
            'App\\Controller\\SecurityController::reset' => '?',
            'App\\Controller\\TaskController::create' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DepartmentController:create' => '?',
            'App\\Controller\\DepartmentController:delete' => '?',
            'App\\Controller\\DepartmentController:index' => '?',
            'App\\Controller\\SecurityController:createPasswordForm' => '?',
            'App\\Controller\\SecurityController:getAuthCookie' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:register' => '?',
            'App\\Controller\\SecurityController:rescue' => '?',
            'App\\Controller\\SecurityController:reset' => '?',
            'App\\Controller\\TaskController:create' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\UserController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
