<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NBk1zMXService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.nBk1zMX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nBk1zMX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator.nBk1zMX.App\\Entity\\UserProfile', NULL, 'Cannot autowire service ".service_locator.nBk1zMX": it references class "App\\Entity\\UserProfile" but no such service exists.'],
        ], [
            'user' => 'App\\Entity\\UserProfile',
        ]);
    }
}
