<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleRecaptchaResolverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Resolver\GoogleRecaptchaResolver' shared autowired service.
     *
     * @return \App\Resolver\GoogleRecaptchaResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Resolver/GoogleRecaptchaResolver.php';

        return $container->privates['App\\Resolver\\GoogleRecaptchaResolver'] = new \App\Resolver\GoogleRecaptchaResolver($container->getEnv('GOOGLE_RECAPTCHA_ENDPOINT'), $container->getEnv('GOOGLE_RECAPTCHA_SECRET'), ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
