<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\PluginSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\PluginSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/PluginSubscriber.php';

        return $container->privates['App\\EventSubscriber\\PluginSubscriber'] = new \App\EventSubscriber\PluginSubscriber();
    }
}
