<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendGridMailerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Mailer\SendGridMailer' shared autowired service.
     *
     * @return \App\Mailer\SendGridMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Mailer/SendGridMailer.php';

        return $container->privates['App\\Mailer\\SendGridMailer'] = new \App\Mailer\SendGridMailer(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $container->getEnv('SENDGRID_API_KEY'));
    }
}
