<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfile2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nBk1zMX.App\Entity\UserProfile' shared service.
     *
     * @return \App\Entity\UserProfile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nBk1zMX": it references class "App\\Entity\\UserProfile" but no such service exists.');
    }
}
