<?php

namespace ContainerMibux8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileSubscriberService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\UserProfileSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\UserProfileSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/UserProfileSubscriber.php';

        return $container->privates['App\\EventSubscriber\\UserProfileSubscriber'] = new \App\EventSubscriber\UserProfileSubscriber();
    }
}
