<?php

namespace Container5JsSECr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PCQafzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PC_qafz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PC_qafz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'link' => ['privates', '.errored..service_locator.PC_qafz.App\\Entity\\Links', NULL, 'Cannot autowire service ".service_locator.PC_qafz": it references class "App\\Entity\\Links" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'link' => 'App\\Entity\\Links',
        ]);
    }
}
