<?php

namespace Container5JsSECr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\ExceptionSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/ExceptionSubscriber.php';

        return $container->privates['App\\EventSubscriber\\ExceptionSubscriber'] = new \App\EventSubscriber\ExceptionSubscriber(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
