<?php

namespace ContainerF3ss8WP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9755fLRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9755fLR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9755fLR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IndexController::access' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\IndexController::mostAccessed' => ['privates', '.service_locator.QBapjZX', 'get_ServiceLocator_QBapjZXService', true],
            'App\\Controller\\LinkController::delete' => ['privates', '.service_locator.PC_qafz', 'get_ServiceLocator_PCQafzService', true],
            'App\\Controller\\LinkController::edit' => ['privates', '.service_locator.PC_qafz', 'get_ServiceLocator_PCQafzService', true],
            'App\\Controller\\LinkController::find' => ['privates', '.service_locator._w0bJ1d', 'get_ServiceLocator_W0bJ1dService', true],
            'App\\Controller\\LinkController::index' => ['privates', '.service_locator.2lAiegZ', 'get_ServiceLocator_2lAiegZService', true],
            'App\\Controller\\LinkController::save' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\IndexController:access' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\IndexController:mostAccessed' => ['privates', '.service_locator.QBapjZX', 'get_ServiceLocator_QBapjZXService', true],
            'App\\Controller\\LinkController:delete' => ['privates', '.service_locator.PC_qafz', 'get_ServiceLocator_PCQafzService', true],
            'App\\Controller\\LinkController:edit' => ['privates', '.service_locator.PC_qafz', 'get_ServiceLocator_PCQafzService', true],
            'App\\Controller\\LinkController:find' => ['privates', '.service_locator._w0bJ1d', 'get_ServiceLocator_W0bJ1dService', true],
            'App\\Controller\\LinkController:index' => ['privates', '.service_locator.2lAiegZ', 'get_ServiceLocator_2lAiegZService', true],
            'App\\Controller\\LinkController:save' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\IndexController::access' => '?',
            'App\\Controller\\IndexController::mostAccessed' => '?',
            'App\\Controller\\LinkController::delete' => '?',
            'App\\Controller\\LinkController::edit' => '?',
            'App\\Controller\\LinkController::find' => '?',
            'App\\Controller\\LinkController::index' => '?',
            'App\\Controller\\LinkController::save' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\IndexController:access' => '?',
            'App\\Controller\\IndexController:mostAccessed' => '?',
            'App\\Controller\\LinkController:delete' => '?',
            'App\\Controller\\LinkController:edit' => '?',
            'App\\Controller\\LinkController:find' => '?',
            'App\\Controller\\LinkController:index' => '?',
            'App\\Controller\\LinkController:save' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
